-- Add holiday mode fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS holiday_mode BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS holiday_from TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS holiday_to TIMESTAMPTZ;

-- +goose Down
ALTER TABLE users DROP COLUMN IF EXISTS holiday_to;
ALTER TABLE users DROP COLUMN IF EXISTS holiday_from;
ALTER TABLE users DROP COLUMN IF EXISTS holiday_mode;
